(void (call expect (call mult 5 5) 25))
(void (call expect (call mult 5 6) 30))
(void (call expect (call mult -2 7) -14))
(void (call expect (call leq 5 5) #true))
(void (call expect (call leq 4 5) #true))
(void (call expect (call leq -5 5) #true))
(void (call expect (call leq 6 5) #false))
(void (call expect (call geq 5 5) #true))
(void (call expect (call geq 4 5) #false))
(void (call expect (call geq -5 5) #false))
(void (call expect (call geq 6 5) #true))
(void (call expect (call remainder 12 5) 2))
(void (call expect (call remainder 31 5) 1))
(void (call expect (call remainder 36 6) 0))
(void (call expect (call factorial 3) 6))
(void (call expect (call factorial 4) 24))
(void (call expect (call factorial 5) 120))